"""Generate docs/POLICY_REFERENCE.md from the policy models and the packaged defaults.

Run `make policy-docs` (or `python -m aireviewer.policy.reference <output path>`) after
changing `contracts/policy.py` or `policy/default_policy.yml`; a unit test fails while the
committed file is out of date.
"""

from __future__ import annotations

import json
import sys
from pathlib import Path
from typing import Any, Final

from aireviewer.contracts.policy import MAX_DETECTOR_LENGTH, POLICY_SCHEMA_VERSION, Policy
from aireviewer.policy.detectors import DETECTOR_TIMEOUT_SECONDS
from aireviewer.policy.loader import (
    MAX_ERRORS,
    MAX_POLICY_BYTES,
    MAX_POLICY_DEPTH,
    default_policy,
)

_MISSING: Final = object()

_INTRO = f"""\
# Policy reference: `.ai-review.yml` (schema v{POLICY_SCHEMA_VERSION})

<!-- Generated by `make policy-docs` from src/aireviewer/contracts/policy.py and
src/aireviewer/policy/default_policy.yml. Do not edit by hand. -->

## How the policy is loaded

- The file is read from the pull request's **base commit**. A policy changed by the pull
  request applies only after it is merged.
- It is merged over the built-in defaults: mappings merge key by key; **lists, scalars and
  `null` replace** the default. Setting `exclude_paths`, for example, drops the default
  excludes. Every key is optional; `version`, if present, must be `{POLICY_SCHEMA_VERSION}`.
- An invalid file never fails the review: the defaults apply instead, and the errors (at
  most {MAX_ERRORS}) are listed at the top of the summary. Unknown keys are errors, so
  typos are visible.
- Limits: at most {MAX_POLICY_BYTES} bytes and {MAX_POLICY_DEPTH} levels of nesting.
- Only plain YAML is accepted: no tags (`!!python/...`, `!include`), no aliases (`*name`),
  no duplicate keys, dates or non-string keys. Quote values such as `2024-01-01` and keys
  such as `on`.
- Numbers and booleans are not converted from strings: `max_files: "60"` is an error.
- Globs are repository-relative, gitignore-style patterns (`**/vendor/**`, `src/app/**`,
  `*.py`). Not allowed: a leading `/`, `\\`, `..` segments or `!` negation.
- `detector` regexes use the `regex` package syntax, at most {MAX_DETECTOR_LENGTH} characters;
  every search stops after {DETECTOR_TIMEOUT_SECONDS} seconds.
- The effective policy's version, `sha256(canonical JSON)[:16]`, is stored on each run.
"""


def render_policy_reference() -> str:
    schema = Policy.model_json_schema(by_alias=True)
    defs: dict[str, Any] = schema.get("$defs", {})
    defaults = default_policy().model_dump(mode="json", by_alias=True)
    parts = [_INTRO]
    for name, prop in schema["properties"].items():
        parts.append(f"\n## `{name}`\n")
        # A nested section is described by its model's docstring; a leaf by its table row.
        section_description = _resolve(prop, defs).get("description") if "$ref" in prop else None
        if section_description:
            parts.append(f"\n{_clean(section_description)}\n")
        rows = _rows(name, prop, defs, defaults.get(name, _MISSING), from_defaults=True)
        parts.append("\n| Key | Type | Default | Description |\n|---|---|---|---|\n")
        parts.extend(f"| {' | '.join(row)} |\n" for row in rows)
    return "".join(parts)


def _rows(
    path: str, prop: dict[str, Any], defs: dict[str, Any], default: object, *, from_defaults: bool
) -> list[tuple[str, str, str, str]]:
    resolved = _resolve(prop, defs)
    if "properties" in resolved:  # a nested mapping: one row per key
        rows = []
        for key, sub in resolved["properties"].items():
            sub_default = default.get(key, _MISSING) if isinstance(default, dict) else _MISSING
            if not from_defaults:
                sub_default = sub.get("default", _MISSING)
            rows += _rows(f"{path}.{key}", sub, defs, sub_default, from_defaults=from_defaults)
        return rows
    row = (f"`{path}`", _type(prop, defs), _default(default), _clean(prop.get("description", "")))
    items = _resolve(resolved.get("items", {}), defs)
    if resolved.get("type") == "array" and "properties" in items:  # list of mappings
        item_rows = [
            _rows(f"{path}[].{key}", sub, defs, sub.get("default", _MISSING), from_defaults=False)
            for key, sub in items["properties"].items()
        ]
        return [row] + [r for rows in item_rows for r in rows]
    return [row]


def _resolve(prop: dict[str, Any], defs: dict[str, Any]) -> dict[str, Any]:
    if "$ref" in prop:
        resolved: dict[str, Any] = defs[prop["$ref"].rsplit("/", 1)[-1]]
        return resolved
    return prop


def _type(prop: dict[str, Any], defs: dict[str, Any]) -> str:
    prop = {**_resolve(prop, defs), **{k: v for k, v in prop.items() if k != "$ref"}}
    if "anyOf" in prop:
        options = [o for o in prop["anyOf"] if o.get("type") != "null"]
        nullable = len(options) < len(prop["anyOf"])
        text = " or ".join(_type(o, defs) for o in options)
        return f"{text} or `null`" if nullable else text
    if "const" in prop:
        return f"`{json.dumps(prop['const'])}`"
    if "enum" in prop:
        return "one of " + ", ".join(f"`{v}`" for v in prop["enum"])
    kind = prop.get("type")
    if kind == "array":
        items = prop.get("items", {})
        if "properties" in _resolve(items, defs):
            text = "list of mappings (keys below)"
        else:
            text = f"list of {_type(items, defs)}"
        if prop.get("minItems"):
            text += f", at least {prop['minItems']}"
        return text
    if kind == "object" and "properties" in prop:
        return "mapping (keys below)"
    if kind == "object":
        patterns = prop.get("patternProperties", {})
        if len(patterns) == 1:
            ((keys, values),) = patterns.items()
            return f"mapping of names matching `{keys}` to {_type(values, defs)}"
        return "mapping"
    if kind in ("integer", "number"):
        text = "integer" if kind == "integer" else "number"
        low, high = prop.get("minimum"), prop.get("maximum")
        if low is not None and high is not None:
            return f"{text} from {low} to {high}"
        return f"{text} ≥ {low}" if low is not None else text
    if kind == "boolean":
        return "boolean"
    if kind == "string":
        if "format" in prop:
            return str(prop["format"])
        if "pattern" in prop:
            return f"string matching `{prop['pattern']}`"
        if "maxLength" in prop:
            return f"text, {prop.get('minLength', 0)} to {prop['maxLength']} characters"
        return "string"
    return "any"


def _default(value: object) -> str:
    if value is _MISSING:
        return "required"
    return f"`{json.dumps(value, ensure_ascii=False)}`"


def _clean(text: str) -> str:
    return " ".join(text.split()).replace("|", "\\|")


def main(argv: list[str]) -> int:
    text = render_policy_reference()
    if len(argv) > 1:
        Path(argv[1]).write_text(text, encoding="utf-8")
    else:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
